apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: kibana
  labels:
    app: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    name: kibana
    targetPort: 5601
  selector:
    app: kibana
