apiVersion: v1
kind: Service
metadata:
  name: "svc-{{ .Release.Name  }}"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: "{{ .Chart.Name }}"
  type: "{{ .Values.service.type }}"
