apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cilium-gateway-access
  namespace: ci
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways", "httproutes"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cilium-gateway-access
  namespace: ci
subjects:
- kind: ServiceAccount
  name: cilium
  namespace: kube-system
roleRef:
  kind: Role
  name: cilium-gateway-access
  apiGroup: rbac.authorization.k8s.io
