apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 9.2.4
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
